[package]
name = "vizkit"
description = "A rendering-agnostic kit for data visualization"
homepage = "https://github.com/bourbonut/vizkit"
documentation = "https://docs.rs/vizkit"
repository = "https://github.com/bourbonut/vizkit"
version = "0.1.1"
edition = "2024"
keywords = ["visualization"]
license = "MIT"
readme = "README.md"

[lib]
name = "vizkit"

[dependencies]
chrono = { version = "0.4.45", optional = true }

[features]
time = ["dep:chrono"]

[workspace]
members = ["examples/*"]

[dev-dependencies]
rstest = "0.26.1"

[package.metadata.docs.rs]
features = ["time"]
rustdoc-args = ["--cfg", "docsrs"]
