mod categorical;
mod cividis;
mod color;
mod common;
mod diverging;
mod rainbow;
mod sequential;
mod sinebow;
mod turbo;
mod viridis;
mod warm_cold;

pub use crate::categorical::Categorical;
pub use crate::cividis::cividis;
pub use crate::color::Color;
pub use crate::diverging::Diverging;
pub use crate::rainbow::rainbow;
pub use crate::sequential::Sequential;
pub use crate::sinebow::sinebow;
pub use crate::turbo::turbo;
pub use crate::viridis::Viridis;
pub use crate::warm_cold::WarmCold;
